//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using UnityEngine;

public class ComponentManager<T> where T : Component
{
	Dictionary<GameObject,T> cache = new Dictionary<GameObject,T>();

	private ComponentManager ()
	{
	}

	private static ComponentManager<T> _instance;
	public static ComponentManager<T> instance{
		get{
			if(_instance == null)
				_instance = new ComponentManager<T>();
			return _instance;
		}
	}

	public void Register(GameObject go, T comp){
		cache.Add (go, comp);
	}

	public T Get(GameObject go){
		if (!cache.ContainsKey (go))
			return null;
		return cache [go];
	}

	public void UnRegister(GameObject go){
		if (cache.ContainsKey (go))
			cache.Remove (go);
	}

}

